# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-cross_origin}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brit Gardner"]
  s.date = %q{2009-12-28}
  s.description = %q{Cross Origin Resource Sharing helper for Sinatra}
  s.email = %q{brit@britg.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "lib/sinatra/cross_origin.rb",
     "test/app/test_app.rb",
     "test/test_all.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/britg/sinatra-cross_origin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Cross Origin Resource Sharing helper for Sinatra}
  s.test_files = [
    "test/app/test_app.rb",
     "test/test_all.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

