# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sinatra-cross_origin 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "sinatra-cross_origin"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Brit Gardner"]
  s.date = "2016-10-20"
  s.description = "Cross Origin Resource Sharing helper for Sinatra"
  s.email = "brit@britg.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/sinatra/cross_origin.rb",
    "sinatra-cross_origin.gemspec",
    "test/app/all_routes.rb",
    "test/app/test_app.rb",
    "test/test_all.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/britg/sinatra-cross_origin"
  s.rubygems_version = "2.4.5.1"
  s.summary = "Cross Origin Resource Sharing helper for Sinatra"
end

